### ISSUE TITLE
Multiple reference trees not supported in command line 

### ISSUE THREAD

**Issue by emilyvansyoc** [TreeCmp/TreeCmp#6]
Hello - Thanks for writing such a great resource. This is more of a feature request than an issue. It seems that multiple reference trees are supported in VisualTreeCMP, while only one is supported in the command line.

For example, using a reference file with 10 trees and an input file of 10 trees:
-The Visual TreeCMP output is 100 lines (reference 1, input 1; reference 1, input 2.... reference 2, input 1; reference 2, input 2...) with an "all-versus-all" approach.
-The command line output is 10 lines (reference 1, input 2... reference 1, input 10) and it seems that only the first tree in the file is used as a reference.

Is this an easy fix? Thanks!

**Comment by dbogdanowicz** [comment]
Hi Emily!
Thanks for such kind words:) 
Regarding the feature: I believe it is implemented in version 2.0: please check out this zip: https://eti.pg.edu.pl/TreeCmp/treecmp/bin/TreeCmp_v2.0-b76.zip
This file comes from this website: https://eti.pg.edu.pl/TreeCmp/download.html

Best regards,
Damian

**Comment by emilyvansyoc** [comment]
Ah, yes that fixed it! I missed the v2 on that download page somehow. 

Thank you so much for your quick reply! I had a follow-up question about interpreting the normalized scores based on the wording in the 2012 and 2017 papers... that is off-topic for this issue thread, do you have an email address that I could write to?

**Comment by dbogdanowicz** [comment]
Hi,
I am glad that v2 version works as expected.
Regarding normalized scores we can follow up via mail: damian.bogdanowicz@eti.pg.edu.pl

Best regards,
Damian
