### ISSUE TITLE
Config Files Not Found

### ISSUE THREAD

**Issue by resplendentHSHI** [TreeCmp/TreeCmp#8]
Using .. for relative paths seems to not work on linux or mac. Is there a way I can specify a path to the config instead?

(base) hshi@hshi-u1:~/Desktop/TreeCmp$ java -jar /home/hshi/Desktop/TreeCmp/build/libs/TreeCmp-2.0-b103.jar -w 2 -d ms -i examples/beast/testBSP.newick -o testBSP.newick_w_2.out -I
Cannot found configuration file:
/home/hshi/Desktop/TreeCmp/build/libs/TreeCmp-2.0-b103.jar../../../resources/main/config/config.xml (No such file or directory)
/home/hshi/Desktop/TreeCmp/build/libs/TreeCmp-2.0-b103.jar../../resources/main/config/config.xml (No such file or directory)

**Comment by dbogdanowicz** [comment]
Hi,
Can you try:
1. download the zip file from here: https://eti.pg.edu.pl/TreeCmp/download.html
2. unpack it,
3. and run treeCmp.jar as presented below (this approach works on Linux running on WSL2):
![obraz](https://github.com/TreeCmp/TreeCmp/assets/5453514/21ce6272-1ac6-4ea5-82bf-ebc4be8d5a29)

I hop this helps.
Best regards,
Damian

**Comment by netwon123** [comment]
> Hi, Can you try:
> 
> 1. download the zip file from here: https://eti.pg.edu.pl/TreeCmp/download.html
> 2. unpack it,
> 3. and run treeCmp.jar as presented below (this approach works on Linux running on WSL2):
>    ![obraz](https://private-user-images.githubusercontent.com/5453514/307908507-21ce6272-1ac6-4ea5-82bf-ebc4be8d5a29.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NzY2ODgsIm5iZiI6MTcxNjQ3NjM4OCwicGF0aCI6Ii81NDUzNTE0LzMwNzkwODUwNy0yMWNlNjI3Mi0xYWM2LTRlYTUtODJiZi1lYmM0YmU4ZDVhMjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjNUMTQ1OTQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzE2MDE4MDI2OTk5OWU2ZGQyYTRkYmRiZWEyMGFhMTU2MDc2YTUwODVkOWU1YTY5NjY1MTk1MDRjZTU5M2Y5YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.jLW0k6UGhW89F6B_Y7CPrgfwVuPNco9MDIZ52vW9YRQ)
> 
> I hop this helps. Best regards, Damian

Sorry, the link cannot be used, could you upload new one?

**Comment by netwon123** [comment]
> Using .. for relative paths seems to not work on linux or mac. Is there a way I can specify a path to the config instead?
> 
> (base) hshi@hshi-u1:~/Desktop/TreeCmp$ java -jar /home/hshi/Desktop/TreeCmp/build/libs/TreeCmp-2.0-b103.jar -w 2 -d ms -i examples/beast/testBSP.newick -o testBSP.newick_w_2.out -I Cannot found configuration file: /home/hshi/Desktop/TreeCmp/build/libs/TreeCmp-2.0-b103.jar../../../resources/main/config/config.xml (No such file or directory) /home/hshi/Desktop/TreeCmp/build/libs/TreeCmp-2.0-b103.jar../../resources/main/config/config.xml (No such file or directory)

Hi, could you solved this error? If you download the compiled software mentioned by the developer, could you share it with me？

**Comment by dbogdanowicz** [comment]
It looks like the website: https://eti.pg.edu.pl/TreeCmp/download.html has some difficulties... 
Here is the link to compiled version: 
[TreeCmp_v2.0-b76.zip](https://github.com/TreeCmp/TreeCmp/files/15433593/TreeCmp_v2.0-b76.zip)

I hope that helps,
Damian

**Comment by netwon123** [comment]
> It looks like the website: https://eti.pg.edu.pl/TreeCmp/download.html has some difficulties... Here is the link to compiled version: [TreeCmp_v2.0-b76.zip](https://github.com/TreeCmp/TreeCmp/files/15433593/TreeCmp_v2.0-b76.zip)
> 
> I hope that helps, Damian

it works! Thank you very muck!
